### ISSUE TITLE
Выбор первоначального проекта:

### ISSUE THREAD

**Issue by RSamokhin** [TeamPlate/devKey#1]
Коллеги, к завтрашнему дню нам необходимо принять решение.
Краткие названия проектов (для конспирации).
1. Карточки с переводом.
2. Персональный бюджет.
3. Карточные игры
4. Сапер+морской бой
5. ВК-шпион
6. Рецепты
Поскольку нас пятеро, у каждого в данном случае есть 3 голоса, просьба его отдать за 2 проекта (1+2) :)
Просьба оценивать сложность и продолжительность проекта и получения MVP

**Comment by RSamokhin** [comment]
Голосую за 
- карточки с переводом 2 балла
- сапер + морской бой 1 балл

**Comment by jgc128** [comment]
:two: за ВК-шпион
:one: за Сапер+морской бой

**Comment by jgc128** [comment]
Хотя. вообще еще стоит рассматривать проект с соц-сетями и ревностью - там для каждого найдется занятие, он веселый и простой

**Comment by PomanoB** [comment]
А почему не рассматривается идея Элтона?
Там мало работы, мало графики, высокая социальность
И предлагаю каждому дать 3 голоса, которые надо распределить на две идеи

**Comment by jgc128** [comment]
Предлагаю Роме создать для этого ВМ, где поднять веб-сервис распределения голосов, и отдельно предусмотреть невозможность накруток - авторизация через гитхаб, капчу и решение интеграла 
![sin](https://cloud.githubusercontent.com/assets/669142/5891734/7a824f36-a4b6-11e4-8142-f53d52fcb441.jpg)

**Comment by RSamokhin** [comment]
изменена механика голоования :)  просьба проапдейтить голоса

**Comment by PomanoB** [comment]
Голосую за 
- Сапер+морской бой - 2 балла
- Рецепты - 1 балл

**Comment by RSamokhin** [comment]
голосование закрывается в 23-00 по москве :)

**Comment by PomanoB** [comment]
А где остальные-то голоса?
Надо всех пушить!

**Comment by ermakov-ds** [comment]
Карточки - перевод - 2 балла
Рецепты - 1 балл

**Comment by iFoxxy** [comment]
карточки - 1 балл
сапер - 2 балла!

**Comment by jgc128** [comment]
Результаты: с небольшим перевесом побеждает "Сапер+морской бой"

![vote_result](https://cloud.githubusercontent.com/assets/669142/5893043/1f2b9fee-a4e7-11e4-8a36-402de1ef8a70.png)

**Comment by RSamokhin** [comment]
Итак, делаем проект Сапер + Морской бой

**Comment by PomanoB** [comment]
Неожиданно)
