### ISSUE TITLE
Выбор названия под проект Сапер+морской бой

### ISSUE THREAD

**Issue by RSamokhin** [TeamPlate/devKey#2]
От каждого участника ожидается 1 предложение
Просьба параллельно проверять наличие свободного доменного имени (например, здесь https://ru.godaddy.com/)
В Microsoft запросил ресурсы Azure на потом
Голосуем за ЧУЖИЕ варианты по принципу 2+1
Ваши варианты буду оценены другими членами команды

Варианты: 
- Gamefication
- OnMine
- NoMoreRobots (NoMoreBots)
- OMGame
- BombEra

**Comment by RSamokhin** [comment]
Мое предложение под обобщенное название сервиса gamefication, в дальнейшем каждый отдельный элемент можно будет вынести

**Comment by jgc128** [comment]
OnMine - Online Minesweeper
CommGames - Communication Games
NoMoreRobots - Play with a human, not a robot

Мне больше всего нравится NoMoreRobots

**Comment by PomanoB** [comment]
OmGame

Голосую:
2 балла -за NoMoreRobots (NoMoreBots)
1 балл за gamefication

**Comment by ermakov-ds** [comment]
BombEra - типа бомбардировка, что с кораблей, что поля. Минус - тогда все последующие игры должны быть связаны со взрывами (bombera.info, bombera.ru, bombera.co свободны)
Голосую за OnMine (onmine.info, onmine.co, onmine.ru свободны)
NoMoreRobots - сократил бы до NoMoreBots или BotsNoMore (botsnomore.com свободен)

**Comment by RSamokhin** [comment]
2 балла за OMGame
1 балл за BombEra (желательно BombEra.net :))

**Comment by ermakov-ds** [comment]
2 балла OnMine
1 балл NoMoreBots

**Comment by jgc128** [comment]
Ага, NoMoreBots отлично - мои 2 балла за него
1 балл на OMGame

**Comment by RSamokhin** [comment]
нельзя голосовать за себя, Алексей

**Comment by jgc128** [comment]
Ну ок, тогда пока Антон не отписался, 2 балла за OmGame, 1 за bombera

**Comment by iFoxxy** [comment]
Minesweeper Online (типа предлагаю) - мне кажется, название должно быть говорящим само за себя, чтобы в поиске вываливаться и бросаться в глаза. Делать несколько приложений в одном, нахожу странным) лучше выпустить отдельно сапера и отдельно морской бой

**Comment by iFoxxy** [comment]
2 - OnMine
1 - BombEra

**Comment by jgc128** [comment]
Тогда 2 голоса за Minesweeper Online и 1 за OmGame

**Comment by RSamokhin** [comment]
![image](https://cloud.githubusercontent.com/assets/5427231/5899697/95dedd0c-a570-11e4-9cab-df26d3d3440e.png)

Выбрано: OnMine
