### ISSUE TITLE
Выбор языка программирования

### ISSUE THREAD

**Issue by PomanoB** [TeamPlate/devKey#3]
Критерии голосования:
1. Язык должно знать 2+ человека
Голосование по системе 2 + 1 (как в прошлых)

**Comment by jgc128** [comment]
C# - 2 балла
PHP - 1 балл

**Comment by iFoxxy** [comment]
э, лол) не справедливые критерии какие-то, вы приложение на пхп хотите писать?

**Comment by jgc128** [comment]
И я также считаю( Если бы не это требование - предложил бы питон в качестве второго варианта. 
А так на пхп вполне можно писать приложения - http://habrahabr.ru/post/106075/

**Comment by iFoxxy** [comment]
Так может для начала с платформой определимся?

**Comment by iFoxxy** [comment]
Понятное дело, что есть куча фреймворков и библиотек, чтобы писать на чем угодно и для чего угодно) предлагаю определить платформу для первого приложения, а язык выбирать, отталкиваясь от платформы - зачем на php писать приложение под ios с кучей костылей, если для этого есть obj c и swift)

**Comment by jgc128** [comment]
Тогда надо определить, будем ли мы писать для каждой мобильной платформы нативное приложение, или нет. И определеится с языком для сервера.

**Comment by RSamokhin** [comment]
Изначально платформа одна - веб

**Comment by RSamokhin** [comment]
Просьба подойти к выбору языка адекватно оценив свои возможности и желание выучить, все равно задачи разделим согласно навыкам

Моя оценка 
2 балла Java
1 балл Nodejs

**Comment by ermakov-ds** [comment]
C# - 2 балла
php - 1 балл (ничего в нем не помню, но думаю быстро разберусь при необходимости)

**Comment by iFoxxy** [comment]
Java - 2 балла
php - 1 балл

для фб есть готовые либы на эти два языка

**Comment by RSamokhin** [comment]
Павел, проголосуй и подведи итоги, пожалуйста

**Comment by PomanoB** [comment]
Node.js - 2 балла
Java - 1 балл

**Comment by RSamokhin** [comment]
павел, необходимо принять решение

**Comment by PomanoB** [comment]
Проголосовал, подведи, пожалуйста, итоги

**Comment by RSamokhin** [comment]
Итоги JAVA

Java 5
ASP 4
NodeJS 3
PHP 3
