### ISSUE TITLE
Выбор базы данных

### ISSUE THREAD

**Issue by PomanoB** [TeamPlate/devKey#4]
Голосование по системе 2 + 1 (как в прошлых)

**Comment by jgc128** [comment]
SQL Server + Redis - 2 балла
SQL Server/MySQL + realtime.co - 1 балл

**Comment by ermakov-ds** [comment]
MS SQL - 2 балла
Postgre - 1 балл

**Comment by RSamokhin** [comment]
SQL на Azure 2 бала
Reddis 1 балл

**Comment by jgc128** [comment]
Ром, это взаимосвязанные вещи.Нам нужна 1 БД для хранения данных, и какая-то сиситема обмена сообщениями. Или Redis, или realtime.co, или Azure. Надо сделать еще 1 голосвание для системы обмена сообщениями.

**Comment by PomanoB** [comment]
PostgreSQL - 2 балла
MySQL - 1 балл

**Comment by RSamokhin** [comment]
> Ром, это взаимосвязанные вещи.Нам нужна 1 БД для хранения данных, и какая-то сиситема обмена сообщениями. Или Redis, или realtime.co, или Azure. Надо сделать еще 1 голосвание для системы обмена сообщениями.

Мы вполне обойдемся 1 базой для первого проекта, алексей, в крайнем случае позже допишем, определись, пожалуйста с 1 решением, усложнять будем во втором проекте

**Comment by jgc128** [comment]
Мы никак не обойдемся без системы обмена сообщениями - поэтому её тоже надо выбрать

**Comment by PomanoB** [comment]
Предлагаю сделать чатик в Hangouts

**Comment by PomanoB** [comment]
Можно на вас двоих, а можно на всех

**Comment by RSamokhin** [comment]
мы вполне обойдемся чисто реляционной БД для первого проекта, у нас и так работы выше крыши, а большинство из нас параллельно работает

**Comment by jgc128** [comment]
Скажи, пожалуйста, как на клиент будут приходит изменения в игровом поле и другие данные?

**Comment by RSamokhin** [comment]
хранить в рамках процесса игрового инстанса , периодически кешируя в базу

**Comment by jgc128** [comment]
Ты немного не понял - вот игрок2 открыл новое поле - как игрок1 об это узнает?

**Comment by RSamokhin** [comment]
ок после диалога в скайпе мое мнение
Чисто Reddis 2 балла
чисто SQL 1 балл
2 бд нам не нужны, по мне так, я вижу решение без них, пускай павел своим голосом решит спор

**Comment by jgc128** [comment]
У нас и не будет 2 БД - редис будет чисто для обмена сообщениями.

**Comment by jgc128** [comment]
Вообще, редис это не БД - это

> key-value cache and store.

(с официального сайта)

**Comment by RSamokhin** [comment]
я рассматриваю редис как БД с быстрым доступом к данным

**Comment by jgc128** [comment]
Я к тому, что у нас не будет 2 БД

**Comment by PomanoB** [comment]
| БД | Голоса |
| --- | --- |
| SQL на Azure | 5 |
| Redis | 4 |
| PostgreSQL | 3 |
| MySQL | 1 |
