### ISSUE TITLE
Выбор платформы для первого приложения

### ISSUE THREAD

**Issue by iFoxxy** [TeamPlate/devKey#5]
Давайте так же голосовать за платформен!
Желательно аргументировать и, если знаете, писать заведомо известные подводные камни)

**Comment by iFoxxy** [comment]
2 - IOS
1 - Android

ios - как минусы: разработка на Objective C или Swift, в чем никто из команды не шарит, платная лицензия разработчика для тестирования приложения на устройствах(у меня есть, так что можно это как-то пережить будет). плюс: крутой опыт создания приложений на айфон, которые делаешь платными и богатеешь!
android - как минус: владельцы икспирий не покупают приложения(

**Comment by ermakov-ds** [comment]
win - 2 балла (скорее всего анальное рабство .net, win api и mfc, хотя .net вроде как открыли и портировали на никсы)
ios - 1 балл (минус - разработка только на маке, коего у меня, например, нету, а виртуалка с хакинтошем дико тормозит)

**Comment by RSamokhin** [comment]
я против голосования по платформам, поскольку с вероятностью 90 процентов все приложения изначально будут иметь веб-вью. 
Изначально стоит определиться с языком серверной части
Изначальная платформа одна - это веб

**Comment by jgc128** [comment]
WP - 2 балла, Android - 1 балл.

Процесс разработки под WP очень хорошо выстроен, под iOS я писать не смогу в ввиду отсутствия устройств, поэтому 1 балл отходит Андройду.  

> win api и mfc

Какой WinApi, какое MFC))) Сейчас под WP все пишется на C# в Visual Studio, а интерфейс - на XAML (если писал на WPF с ходу разберешся)

**Comment by iFoxxy** [comment]
Как тут отвечать кому-то?(
"Изначальная платформа одна - это веб" - поясни

**Comment by PomanoB** [comment]
> Как тут отвечать кому-то?(

Ставишь > впереди текста

> Изначальная платформа одна - это веб

Я согласен. Предлагаю первоначальный запуск в социальных сетях

**Comment by PomanoB** [comment]
ВК - 2 балла
Лицокнига - 1 балл

**Comment by RSamokhin** [comment]
первое приложние делается с отображением UI через браузер 
оно легче в разработке и отладке (на этапе разработки и отладки серверной части)
К тому же легко портируется в соц-сети

**Comment by ermakov-ds** [comment]
> Какой WinApi, какое MFC))) Сейчас под WP все пишется на C# в Visual Studio

че-то не сообразил, что у нас основное направление - мобильные устройства

**Comment by RSamokhin** [comment]
поддеживаю павла
после веба 
2 балла ВК
1 балл ФБ

**Comment by jgc128** [comment]
+1 за соц сети. Заодно получим опыт для дальнейшей реализации ВК-шпиона

Тогда:
Facebook - 2 балла (+100500 к аудитории, изначально надо делать на английском языке)
ВК - 1 балл

**Comment by RSamokhin** [comment]
мы будем изначально исползовать свою или готовую библиотеку для перевода

**Comment by jgc128** [comment]
> оно легче в разработке и отладке (на этапе разработки и отладки серверной части)

насчет разработки - да, отлаживать же не так удобно, как в случае нативное приложение

**Comment by RSamokhin** [comment]
> насчет разработки - да, отлаживать же не так удобно, как в случае нативное приложение

Что тебе неудобен? Дебаг в консоли? отсутствие необходимости сборки?

**Comment by iFoxxy** [comment]
> первое приложние делается с отображением UI через браузер 
> оно легче в разработке и отладке (на этапе разработки и отладки серверной части)

Ну, ты просто прошарен в веб-разработке) будем считать, что отталкиваемся от опыта команды в целом

Тогда выбор между фб - 2 балла и вк - 1 балл

**Comment by ermakov-ds** [comment]
вк - 1 балла
фб - 2 балл
полбалла твиттеру =)

**Comment by jgc128** [comment]
> Что тебе неудобен? Дебаг в консоли? отсутствие необходимости сборки?

Хотя бы то, что не нельзя поставить точки останова, да и даже банально вывести переменную на экран (сужу по Кордове на WP - дебаг не поддерживается вообще)

**Comment by iFoxxy** [comment]
> нельзя поставить точки останова,

как это нельзя.(
можно ж

**Comment by jgc128** [comment]
Нет, кордова на WP работает чисто в WebVIew и не поддреживает дебаг в принципе

**Comment by jgc128** [comment]
Ну, точнее, так было до версии 2.какая-то - теперь она старается идти нативным приложением на JS+HTML. Однако, для разработки под Андройд из Visual Studio все сказанное в силе - там не перенаправляется даже console.log

**Comment by iFoxxy** [comment]
> вк - 1 балла
> фб - 2 балл
> полбалла твиттеру =)

благодаря Диме, фб победил с отрывом в 1 голос!

**Comment by RSamokhin** [comment]
Ок, делаем
Веб->ВК->ФБ->принимаем решение о мобильных платформах

**Comment by iFoxxy** [comment]
ладно, я подтасовал димин голос( вк победил, если честно(

**Comment by iFoxxy** [comment]
И какой к черту веб вылез?

**Comment by RSamokhin** [comment]
Веб-версия в любом случае делается первым делом, потом она просто помещается в приложение в соц-сети

**Comment by ermakov-ds** [comment]
> ладно, я подтасовал димин голос( вк победил, если честно(

я знаю, где ты работаешь
